### ISSUE TITLE
SUSE 15.1: role does not set startup to "automatic"

### ISSUE THREAD

**Issue by johanneskastl** [OndrejHome/ansible.iscsiadm#4]
To have the iscsi devices visible after a reboot, these two lines need to be adapted and set to `automatic` instead of `manual`.

I will try to come up with a fix...

```
# grep manual /etc/iscsi/nodes/iqn.foo.bar.baz:target/1.2.3.4\,3260\,1/default
node.startup = manual
node.conn[0].startup = manual
```

**Comment by OndrejHome** [comment]
Hi @johanneskastl ,
Thank you for rising the issue. On EL systems I can see at least the `node.startup = automatic` while `node.conn[0].startup = manual`. As far as I remember this is influenced on EL systems by the `iscsid.service`. Maybe something similar could be in SUSE.

In any case let me know once you have more information. When I have some time I will also have a look and leave you my observations here. Thank you!

**Comment by johanneskastl** [comment]
First off, I saw the non-automatic behaviour on SLES15 SP1 systems (should be the same behaviour on openSUSE Leap 15.1, I'll test).

**But**:
It seems there is a difference which packages are installed. If I have yast2-iscsi-client installed, the devices are not appearing directly after the role has finished.

With only the following two packages the devices appear and apparently there is no need for a restart:
```
libopeniscsiusr0_2_0-2.0.876-13.37.1.x86_64
open-iscsi-2.0.876-13.37.1.x86_64
```

Seems like one of the following packages (that are being installed as dependencies for yast2-iscsi-client) leads to a changed behaviour:
```
  augeas augeas-lenses iscsiuio libjemalloc2 libstorage-ng-ruby libstorage-ng1 libyui-ncurses-pkg9 libyui-ncurses9 libyui9 lsscsi perl-XML-NamespaceSupport perl-XML-Parser perl-XML-SAX
perl-XML-SAX-Base perl-XML-SAX-Expat perl-XML-Simple perl-gettext ruby ruby2.5-rubygem-abstract_method ruby2.5-rubygem-cfa ruby2.5-rubygem-cheetah ruby2.5-rubygem-fast_gettext
ruby2.5-rubygem-ruby-augeas ruby2.5-rubygem-ruby-dbus ruby2.5-rubygem-simpleidn unzip yast2 yast2-core yast2-country-data yast2-hardware-detection yast2-iscsi-client yast2-logs
yast2-packager yast2-perl-bindings yast2-pkg-bindings yast2-ruby-bindings yast2-storage-ng yast2-transfer yast2-xml yast2-ycp-ui-bindings
```

**Comment by johanneskastl** [comment]
Did some further debugging:

First off, with only the two packages mentioned above the devices are i**mmediately visible after the role has finished**.

Secondly, even with only these two packages installed the devices are **NOT visible after a reboot.**

The iscsi.service on SLES15SP1 has the following commands, not sure if those are the same on CentOS/RHEL:
```
# # systemctl cat iscsi
# /usr/lib/systemd/system/iscsi.service
[...]
[Service]
Type=oneshot
ExecStart=/sbin/iscsiadm -m node --loginall=automatic
ExecStop=/sbin/iscsiadm -m node --logoutall=automatic
ExecStop=/sbin/iscsiadm -m node --logoutall=manual

```

**Comment by OndrejHome** [comment]
Hi Johannes,
Thank you for additional testing and outputs. I wonder what magic is hidden here and will spin up some test machines this week to investigate further.

**Comment by johanneskastl** [comment]
I have created #5 that worked on my first test on openSUSE Leap 15.1. I will do further tests on CentOS7 (where it should not do anything different due to the when condition) and on SLES15 and Leap 15.2.

**Comment by OndrejHome** [comment]
I have finally got to my testing machines and found an interesting 'default' difference between CentOS and OpenSUSE as can be seen below. On OpenSUSE 15.2 if `node.startup` is changed to `automatic` **before** first attempt to login to target then during boot I can see same automatic login into target as on CentOS.

== OpenSUSE 15.2
~~~
# grep -C1 node.startup /etc/iscsi/iscsid.conf
# To request that the iscsi initd scripts startup a session set to "automatic".
# node.startup = automatic
#
# To manually startup the session set to "manual". The default is manual.
node.startup = manual
~~~
== CentOS 6.10/7.9/8.3
~~~
# grep -C1 node.startup /etc/iscsi/iscsid.conf
# To request that the iscsi initd scripts startup a session set to "automatic".
# node.startup = automatic
#
# To manually startup the session set to "manual". The default is automatic.
node.startup = automatic
~~~

I had a look at #5 and I can see that you have approached the change per-login target which should work without changing system default. However for simplicity I'm considering if it wouldn't be a better approach to change the `node.startup` in `/etc/iscsi/iscsid.conf` across all supported OSes (not not OpenSUSE and SLES). I can imagine then configuration option that would change the system-wide startup to `manual` or `automatic` with default being `automatic`. However this approach would only affect new (not yet existing) logins.

**Questions:**
1. Would it be OK to have role just changing system-default for new logins to `automatic` on **all** platforms to match default from CentOS systems? If yes, would it make sense to have this option configurable for *your use case* to anything else than `automatic`?
2. Do you need/require functionality that would change the startup to `automatic` on existing connections in systems? (this is what you current proposal in #5 is doing)

**Comment by johanneskastl** [comment]
Hi Ondrej,

ad 1)
I just tried to modify the session while creating it, I never tried to change the default in /etc/iscsi/iscsid.conf. But if this works I am fine with it. I'll try to come up with another PR...

ad 2)
Hmm, I was not aware of that side effect. I guess if someone already created the sessions before using the role then this might come as a surprise. On the other hand, I see no harm: On CentOS the values should already be like this (unless manually changed) and on *SUSE the user would have to set those values anyway to get the connections working again after reboot.

I guess 2) would be solved if we switch to iscsid.conf (see 1) ).

**Comment by OndrejHome** [comment]
Hi Johannes,
Thank you for fast response.

> On CentOS the values should already be like this (unless manually changed) and on *SUSE the user would have to set those values anyway to get the connections working again after reboot.

I'm concerned here because the role was not changing what was done by hand originally and only took the default from `/etc/iscsi/iscsid.conf`. Based on that I would be for implementing just the first approach - role adjusting `/etc/iscsi/iscsid.conf` for automatic startup, but making this option configurable (default being `automatic`). As for name I think `iscsi_node_startup` comes to my mind, but if have other idea feel free to suggest.

---

PS: In one other role I was once addressing situation where different versions of CentOS (6 vs 7) were using different defaults for one configuration option. In that case I have implemented also `nochange` option that left the platform default and actually didn't change anything when selected. Leaving link here for inspiration in case you would have been looking/liking/considering something like that ;) https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/blob/master/tasks/main.yml#L80-L86

**Comment by OndrejHome** [comment]
Hi Johannes,
I went through the PRs and merged 2 of them addressing the issue, closed one of them with early proposal as it was superseded by other PR. As of now the changes are in `master` branch and I have just tagged them with `5.0.0` version in `master` so they can be used via [Ansible Galaxy](https://galaxy.ansible.com/OndrejHome/iscsiadm).

Altogether thank you for contributing the changes and testing them!

Please let me know if role now in version `5.0.0` works well for you and also if you have any additions to small changes that I have added. In case there are no further requests and all looks good, feel free to close this issue to indicate that all is ok :+1:

**Comment by johanneskastl** [comment]
Tested and confirmed working on both SLES15 SP1 and openSUSE Leap 15.2.
